// GENERATED FILE — do not edit by hand.
// Regenerate with: npm run gen:posts
// Source: content/posts/*.mdx  (89 posts)
//
// See scripts/generate-post-registry.mjs for why these imports are listed
// statically instead of built from the slug at request time.

import type { ComponentType } from "react";

type PostModule = { default: ComponentType };

export const postModules: Record<string, () => Promise<PostModule>> = {
  "2027-tax-brackets-projected": () => import("./posts/2027-tax-brackets-projected.mdx"),
  "401k-ira-contribution-limits-2027": () => import("./posts/401k-ira-contribution-limits-2027.mdx"),
  "aca-premiums-2027-subsidy-cliff": () => import("./posts/aca-premiums-2027-subsidy-cliff.mdx"),
  "ai-account-choice-names-2026": () => import("./posts/ai-account-choice-names-2026.mdx"),
  "ai-advice-benchmark-that-failed-2026": () => import("./posts/ai-advice-benchmark-that-failed-2026.mdx"),
  "ai-entry-level-job-market-2026": () => import("./posts/ai-entry-level-job-market-2026.mdx"),
  "ai-side-hustles-2026-real-numbers": () => import("./posts/ai-side-hustles-2026-real-numbers.mdx"),
  "ai-sycophancy-money-math-2026": () => import("./posts/ai-sycophancy-money-math-2026.mdx"),
  "ai-tax-brackets-more-context-worse-2026": () => import("./posts/ai-tax-brackets-more-context-worse-2026.mdx"),
  "apple-event-september-2026-money-breakdown": () => import("./posts/apple-event-september-2026-money-breakdown.mdx"),
  "august-jobs-report-recession-proof-2026": () => import("./posts/august-jobs-report-recession-proof-2026.mdx"),
  "back-to-school-spending-2026": () => import("./posts/back-to-school-spending-2026.mdx"),
  "big-tech-725-billion-ai-index-fund": () => import("./posts/big-tech-725-billion-ai-index-fund.mdx"),
  "bitcoin-crash-2026-buy-or-wait": () => import("./posts/bitcoin-crash-2026-buy-or-wait.mdx"),
  "bitcoin-etf-flows-explained-2026": () => import("./posts/bitcoin-etf-flows-explained-2026.mdx"),
  "bnpl-credit-score-2026": () => import("./posts/bnpl-credit-score-2026.mdx"),
  "budgeting-50-30-20-rule": () => import("./posts/budgeting-50-30-20-rule.mdx"),
  "budgeting-app-privacy-policy-length-2026": () => import("./posts/budgeting-app-privacy-policy-length-2026.mdx"),
  "car-loan-interest-deduction-2026": () => import("./posts/car-loan-interest-deduction-2026.mdx"),
  "charitable-deduction-changes-2026": () => import("./posts/charitable-deduction-changes-2026.mdx"),
  "clarity-act-crypto-2026": () => import("./posts/clarity-act-crypto-2026.mdx"),
  "credit-card-bnpl-debt-2026": () => import("./posts/credit-card-bnpl-debt-2026.mdx"),
  "crypto-1099-da-cost-basis-2026": () => import("./posts/crypto-1099-da-cost-basis-2026.mdx"),
  "crypto-coming-to-401k-not-yet": () => import("./posts/crypto-coming-to-401k-not-yet.mdx"),
  "crypto-whitepaper-readability-2026": () => import("./posts/crypto-whitepaper-readability-2026.mdx"),
  "emerging-market-opportunities-2026": () => import("./posts/emerging-market-opportunities-2026.mdx"),
  "ethereum-2026-staking-etf": () => import("./posts/ethereum-2026-staking-etf.mdx"),
  "fafsa-2027-28-aid-strategy": () => import("./posts/fafsa-2027-28-aid-strategy.mdx"),
  "fed-meeting-july-2026-what-a-hold-means": () => import("./posts/fed-meeting-july-2026-what-a-hold-means.mdx"),
  "fed-rate-hike-2026-savings-mortgage": () => import("./posts/fed-rate-hike-2026-savings-mortgage.mdx"),
  "fifa-finance-explorer": () => import("./posts/fifa-finance-explorer.mdx"),
  "fixed-income-sleeve-2026": () => import("./posts/fixed-income-sleeve-2026.mdx"),
  "gig-delivery-real-pay-2026": () => import("./posts/gig-delivery-real-pay-2026.mdx"),
  "gold-crash-2026-safe-haven-or-bubble": () => import("./posts/gold-crash-2026-safe-haven-or-bubble.mdx"),
  "government-shutdown-2026-your-money": () => import("./posts/government-shutdown-2026-your-money.mdx"),
  "gta-6-economics-take-two-2026": () => import("./posts/gta-6-economics-take-two-2026.mdx"),
  "holiday-reselling-flip-2026": () => import("./posts/holiday-reselling-flip-2026.mdx"),
  "how-much-tariffs-cost-your-household-2026": () => import("./posts/how-much-tariffs-cost-your-household-2026.mdx"),
  "how-much-youtubers-make-2026": () => import("./posts/how-much-youtubers-make-2026.mdx"),
  "how-to-invest-first-1000": () => import("./posts/how-to-invest-first-1000.mdx"),
  "how-to-start-a-side-hustle": () => import("./posts/how-to-start-a-side-hustle.mdx"),
  "hsa-vs-fsa-2027": () => import("./posts/hsa-vs-fsa-2027.mdx"),
  "index-fund-investing-guide": () => import("./posts/index-fund-investing-guide.mdx"),
  "inflation-by-category-2026": () => import("./posts/inflation-by-category-2026.mdx"),
  "insurance-affordability-crisis-2026": () => import("./posts/insurance-affordability-crisis-2026.mdx"),
  "iphone-financing-cost-2026": () => import("./posts/iphone-financing-cost-2026.mdx"),
  "is-college-worth-it-2026": () => import("./posts/is-college-worth-it-2026.mdx"),
  "jackson-hole-september-fomc-2026": () => import("./posts/jackson-hole-september-fomc-2026.mdx"),
  "lampard-is-now-on-google-adsense": () => import("./posts/lampard-is-now-on-google-adsense.mdx"),
  "local-ai-electricity-cost-2026": () => import("./posts/local-ai-electricity-cost-2026.mdx"),
  "local-ai-money-math-2026": () => import("./posts/local-ai-money-math-2026.mdx"),
  "local-ai-refuses-what-it-knows-2026": () => import("./posts/local-ai-refuses-what-it-knows-2026.mdx"),
  "local-ai-rumour-check-2026": () => import("./posts/local-ai-rumour-check-2026.mdx"),
  "mandatory-roth-catch-up-2026": () => import("./posts/mandatory-roth-catch-up-2026.mdx"),
  "medicare-2027-part-b-open-enrollment": () => import("./posts/medicare-2027-part-b-open-enrollment.mdx"),
  "medicare-advantage-vs-original-2027": () => import("./posts/medicare-advantage-vs-original-2027.mdx"),
  "no-buy-2026-the-math": () => import("./posts/no-buy-2026-the-math.mdx"),
  "no-tax-on-tips-overtime-2026": () => import("./posts/no-tax-on-tips-overtime-2026.mdx"),
  "platform-take-rate-trend-2026": () => import("./posts/platform-take-rate-trend-2026.mdx"),
  "platform-take-rates-2026": () => import("./posts/platform-take-rates-2026.mdx"),
  "private-credit-interval-funds-2026": () => import("./posts/private-credit-interval-funds-2026.mdx"),
  "q2-gdp-june-inflation-what-they-tell-you": () => import("./posts/q2-gdp-june-inflation-what-they-tell-you.mdx"),
  "q3-2026-earnings-preview": () => import("./posts/q3-2026-earnings-preview.mdx"),
  "qualified-charitable-distribution-2026": () => import("./posts/qualified-charitable-distribution-2026.mdx"),
  "quarterly-estimated-taxes-2026": () => import("./posts/quarterly-estimated-taxes-2026.mdx"),
  "rasuwa-flood-august-2026": () => import("./posts/rasuwa-flood-august-2026.mdx"),
  "real-cost-of-driving-2026": () => import("./posts/real-cost-of-driving-2026.mdx"),
  "record-home-price-buy-or-rent-2026": () => import("./posts/record-home-price-buy-or-rent-2026.mdx"),
  "roth-conversion-irmaa-2026": () => import("./posts/roth-conversion-irmaa-2026.mdx"),
  "roth-ira-vs-traditional-ira": () => import("./posts/roth-ira-vs-traditional-ira.mdx"),
  "salt-deduction-cap-2026": () => import("./posts/salt-deduction-cap-2026.mdx"),
  "seasonal-holiday-work-2026": () => import("./posts/seasonal-holiday-work-2026.mdx"),
  "social-security-cola-2027": () => import("./posts/social-security-cola-2027.mdx"),
  "solana-staking-etf-yield-2026": () => import("./posts/solana-staking-etf-yield-2026.mdx"),
  "solo-401k-vs-sep-ira-2026": () => import("./posts/solo-401k-vs-sep-ira-2026.mdx"),
  "sports-betting-cost-2026": () => import("./posts/sports-betting-cost-2026.mdx"),
  "stablecoins-genius-act-savers-2026": () => import("./posts/stablecoins-genius-act-savers-2026.mdx"),
  "student-loan-payment-shock-2026": () => import("./posts/student-loan-payment-shock-2026.mdx"),
  "student-side-hustles-1000-month-2026": () => import("./posts/student-side-hustles-1000-month-2026.mdx"),
  "tax-loss-harvesting-2026": () => import("./posts/tax-loss-harvesting-2026.mdx"),
  "tech-concentration-crisis-2026": () => import("./posts/tech-concentration-crisis-2026.mdx"),
  "the-20000-1099k-rule-is-back": () => import("./posts/the-20000-1099k-rule-is-back.mdx"),
  "tiktok-shop-affiliate-earnings-2026": () => import("./posts/tiktok-shop-affiliate-earnings-2026.mdx"),
  "trump-account-vs-529": () => import("./posts/trump-account-vs-529.mdx"),
  "understanding-federal-reserve-policy": () => import("./posts/understanding-federal-reserve-policy.mdx"),
  "when-to-book-holiday-flights-2026": () => import("./posts/when-to-book-holiday-flights-2026.mdx"),
  "why-are-flights-so-expensive-2026": () => import("./posts/why-are-flights-so-expensive-2026.mdx"),
  "why-electric-bill-climbing-2026-ai": () => import("./posts/why-electric-bill-climbing-2026-ai.mdx"),
  "winter-heating-costs-2026-2027": () => import("./posts/winter-heating-costs-2026-2027.mdx"),
};

export function hasPostModule(slug: string): boolean {
  return Object.prototype.hasOwnProperty.call(postModules, slug);
}
